---
title: Growing With W
description: 'Surviving and sometimes thriving with an awesome twice exceptional (2E)
  kid.  It will appear in your document head meta (for Google search results) and
  in your feed.xml site description.

'
permalink: ":title/"
baseurl: ''
url: https://growingwithw.com
site-twitter: crackinggood
author: Carrie Wheeler
author-img: "/uploads/growing_w_w.png"
about-author: 'Writer, illustrator and problem solver. I create engaging press releases
  for restaurant openings and special events, hype a monthly dance night  and make
  easily digestible copy for websites. I report on food, culture, style and things-to-do
  for local publications and businesses. I suggest things-to-do and places to go for
  hotel visitor’s guides and maps. I teach Photoshop classes to corporate clients.
  I also lend a hand with marketing materials and website updates for a couple of
  local non-profit organizations.

'
social-twitter: crackinggood
social-linkedin: 
social-email: blog@growingwithw.com
discus-identifier: growing-with-w
analytics: 
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-paginate
- jemoji
paginate: 8
paginate_path: "/page/:num"
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
timezone: Etc/UTC
