---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _layouts
  label: Layouts
  create: all
  match: "**/*"
- type: directory
  path: _includes
  label: Includes
  create: all
  match: "**/*"
- type: document
  path: _config.yml
  label: Config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
